package pf.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-08T11:34:16.278+02:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://com.pf/", name = "Hello")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Hello {

    @WebMethod
    @Action(input = "http://com.pf/Hello/bonjourRequest", output = "http://com.pf/Hello/bonjourResponse")
    @WebResult(name = "return", targetNamespace = "http://com.pf/", partName = "return")
    public java.lang.String bonjour(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
